on: [push]

name: Test

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        version: 1.8

    - name: Test with Gradle
      run: ./gradlew test -S
