on:
  push:
    branches:
     - main
     - dev

name: Create Release Snapshot

jobs:
  build:
    name: Create Release Snapshot
    runs-on: ubuntu-latest

    steps:
     - name: run info
       run: |
         echo "run number: $GITHUB_RUN_NUMBER"
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: gradle/wrapper-validation-action@v1
     - name: Set up JDK 8
       uses: actions/setup-java@v1
       with:
         java-version: 8
     - name: Grant execute permission to gradlew
       run: chmod +x gradlew
     - name: Build and upload
       env:
         MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
         MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
       run: ./gradlew build shadowJar exportVersion publishAllPublicationsToNikkyMavenRepository -Pnodryrun --scan
     - name: Set enviroment for github-release
       run: |
         echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
         echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
     - name: Set enviroment RELEASE_TAG
       run: |
         echo "RELEASE_TAG=snapshot/${{ env.VERSION }}-${{ env.BRANCH }}" >> $GITHUB_ENV
     - name: print env
       run: |
         echo "BRANCH=${{ env.BRANCH }}"
         echo "VERSION=${{ env.VERSION }}"
         echo "RELEASE_TAG=${{ env.RELEASE_TAG }}"
     - name: Generate wrappers
       run: |
         mkdir empty_voodoo_project
         java -jar voodoo/build/libs/voodoo-${{ env.VERSION }}-all.jar --rootDir empty_voodoo_project init project
         cd empty_voodoo_project && zip -r ../empty_voodoo_project.zip ./*
     - name: Create prerelease
       uses: meeDamian/github-release@2.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ env.RELEASE_TAG }}
         commitish: ${{ env.GITHUB_SHA }}
         name: ${{ env.VERSION }}
         prerelease: false
         body: Snapshot Release ${{ env.VERSION }}
         gzip: folders
         files: >
           wrapper.jar:wrapper/build/libs/wrapper-${{ env.VERSION }}-all.jar
           voodoo-${{ env.VERSION }}.jar:voodoo/build/libs/voodoo-${{ env.VERSION }}-all.jar
           installer-${{ env.VERSION }}.jar:installer/build/libs/installer-${{ env.VERSION }}-all.jar
           server-installer-${{ env.VERSION }}.jar:server-installer/build/libs/server-installer-${{ env.VERSION }}-all.jar
           empty_voodoo_project.zip:empty_voodoo_project.zip
         allow_override: true
#     - name: notify progress
#       if: always()
#       uses: appleboy/discord-action@master
#       with:
#         webhook_id: ${{ secrets.WEBHOOK_ID }}
#         webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
#         message: The deploy environment development executed ${{ job.status }}.
     - name: Send Webhook Notification
       if: always()
       env:
         JOB_STATUS: ${{ job.status }}
         WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
         HOOK_OS_NAME: ${{ runner.os }}
         WORKFLOW_NAME: ${{ github.workflow }}
       run: |
         git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
         bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
       shell: bash