on:
  push:
    branches:
     - main

name: Create Release Snapshot

jobs:
  build:
    name: Create Release Snapshot
    runs-on: ubuntu-latest

    steps:
     - name: run info
       run: |
         echo "run number: $GITHUB_RUN_NUMBER"
     - uses: actions/checkout@v2
     - uses: gradle/wrapper-validation-action@v1
     - name: Set up JDK 8
       uses: actions/setup-java@v1
       with:
         java-version: 8
     - name: Grant execute permission to gradlew
       run: chmod +x gradlew
     - name: Build and upload
       env:
         MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
         MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
       run: ./gradlew build shadowJar exportVersion publishAllPublicationsToNikkyMavenRepository -Pnodryrun
     - name: Set enviroment for github-release
       run: |
         echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
         echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
     - name: Set enviroment RELEASE_TAG
       run: |
         echo "RELEASE_TAG=snapshot/${{ env.VERSION }}-${{ env.BRANCH }}" >> $GITHUB_ENV
     - name: print env
       run: |
         echo "BRANCH=${{ env.BRANCH }}"
         echo "VERSION=${{ env.VERSION }}"
         echo "RELEASE_TAG=${{ env.RELEASE_TAG }}"
     - name: test
       run: |
         pwd
         cd empty_project && pwd
         pwd
     - name: Generate wrappers
       run: |
         mkdir empty_voodoo_project
         java -jar voodoo/build/libs/voodoo-${{ env.VERSION }}-all.jar --rootDir empty_voodoo_project generateWrapper
         zip -r ../empty_voodoo_project.zip ./empty_voodoo_project
     - name: Create prerelease
       uses: meeDamian/github-release@2.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ env.RELEASE_TAG }}
         commitish: ${{ env.GITHUB_SHA }}
         name: ${{ env.VERSION }}
         prerelease: false
         body: Snapshot Release ${{ env.VERSION }}
         gzip: folders
         files: >
           wrapper.jar:wrapper/build/libs/wrapper-${{ env.VERSION }}-all.jar
           voodoo-${{ env.VERSION }}.jar:voodoo/build/libs/voodoo-${{ env.VERSION }}-all.jar
           multimc-installer-${{ env.VERSION }}.jar:multimc/installer/build/libs/multimc-installer-${{ env.VERSION }}-all.jar
           server-installer-${{ env.VERSION }}.jar:server-installer/build/libs/server-installer-${{ env.VERSION }}-all.jar
           empty_voodoo_project.zip:empty_voodoo_project.zip