name: PUSH

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8-jdk, 11-jdk, 14-jdk ]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: 'Clone Repo'
        uses: actions/checkout@v2

      - name: 'Validate Gradle Wrapper'
        uses: gradle/wrapper-validation-action@v1

      - name: 'Build'
        run: './gradlew clean build --full-stacktrace'

#      - name: 'Publish to BinTray'
#        run: './gradlew bintrayUpload -Pnodryrun --stacktrace'
#        env:
#          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
#          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

